const PRODUCTS=[
{id:1,name:"Jollof Rice & Chicken",price:45,cat:"Rice",image:"jollof.jpg",desc:"Spiced jollof rice served with tender chicken."},
{id:2,name:"Fried Rice & Chicken",price:50,cat:"Rice",image: "jollof.jpg":"🍗",desc:"Flavorful fried rice with crispy chicken."},
{id:3,name:"Chicken Burger",price:35,cat:"Burgers",image: "jollof.jpg":"🍔",desc:"Juicy chicken burger with fresh toppings."},
{id:4,name:"Beef Pizza",price:60,cat:"Pizza",image: "jollof.jpg":"🍕",desc:"Loaded beef pizza with melted cheese."},
{id:5,name:"Grilled Chicken",price:55,cat:"Chicken",image: "jollof.jpg":"🍗",desc:"Seasoned grilled chicken with a smoky finish."},
{id:6,name:"Chicken Wings",price:40,cat:"Chicken",image: "jollof.jpg":"🍗",desc:"Crispy wings served with your favorite sauce."},
{id:7,name:"Meat Lovers Pizza",price:70,cat:"Pizza",image: "jollof.jpg":"🍕",desc:"A rich pizza loaded with savory toppings."},
{id:8,name:"Malt",price:12,cat:"Drinks",image: "jollof.jpg":"🥤",desc:"Chilled malt drink."}
];

function money(n){return "GH₵"+Number(n).toFixed(2).replace(".00","")}
function getCart(){return JSON.parse(localStorage.getItem("uptownCart")||"[]")}
function saveCart(c){localStorage.setItem("uptownCart",JSON.stringify(c));updateCount()}
function updateCount(){let n=getCart().reduce((s,x)=>s+x.qty,0);document.querySelectorAll("#cartCount").forEach(e=>e.textContent=n)}
function addToCart(id){let c=getCart(),item=c.find(x=>x.id===id);if(item)item.qty++;else c.push({id,qty:1});saveCart(c);alert("Added to cart!")}
function productCard(p){return `<article class="food-card"><div class="food-img">${p.image: "jollof.jpg"}</div><div class="food-body"><h3>${p.name}</h3><p>${p.desc}</p><div class="price"><span>${money(p.price)}</span><button class="add" onclick="addToCart(${p.id})">Add to cart</button></div></div></article>`}
function renderMenu(cat="All"){let el=document.getElementById("menuGrid");if(!el)return;let list=cat==="All"?PRODUCTS:PRODUCTS.filter(p=>p.cat===cat);el.innerHTML=list.map(productCard).join("")}
function renderFeatured(){let el=document.getElementById("featuredGrid");if(el)el.innerHTML=PRODUCTS.slice(0,4).map(productCard).join("")}
function renderCart(){let el=document.getElementById("cartItems");if(!el)return;let c=getCart();if(!c.length){el.innerHTML="<div class='summary'><h2>Your cart is empty.</h2><p>Add some delicious meals from the menu.</p><a class='btn' href='menu.html'>Browse menu</a></div>";document.getElementById("subtotal").textContent="GH₵0";document.getElementById("delivery").textContent="GH₵0";document.getElementById("total").textContent="GH₵0";return}let sub=0;el.innerHTML=c.map(x=>{let p=PRODUCTS.find(p=>p.id===x.id),line=p.price*x.qty;sub+=line;return `<div class="cart-row"><div class="cart-image: "jollof.jpg"">${p.image: "jollof.jpg"}</div><div style="flex:1"><h3>${p.name}</h3><strong>${money(p.price)}</strong><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><span>${x.qty}</span><button onclick="changeQty(${p.id},1)">+</button><button class="remove" onclick="removeItem(${p.id})">Remove</button></div></div><strong>${money(line)}</strong></div>`}).join("");let delivery=sub?10:0;document.getElementById("subtotal").textContent=money(sub);document.getElementById("delivery").textContent=money(delivery);document.getElementById("total").textContent=money(sub+delivery)}
function changeQty(id,d){let c=getCart(),x=c.find(x=>x.id===id);if(!x)return;x.qty+=d;if(x.qty<1)c=c.filter(x=>x.id!==id);saveCart(c);renderCart()}
function removeItem(id){saveCart(getCart().filter(x=>x.id!==id));renderCart()}
function renderCheckout(){let el=document.getElementById("checkoutSummary");if(!el)return;let c=getCart();let sub=c.reduce((s,x)=>{let p=PRODUCTS.find(p=>p.id===x.id);return s+p.price*x.qty},0);let delivery=sub?10:0;el.innerHTML=c.map(x=>{let p=PRODUCTS.find(p=>p.id===x.id);return `<div class="sum-row"><span>${p.name} × ${x.qty}</span><strong>${money(p.price*x.qty)}</strong></div>`}).join("");document.getElementById("checkoutTotal").textContent=money(sub+delivery)}
function setupCheckout(){let f=document.getElementById("orderForm");if(!f)return;f.addEventListener("submit",e=>{e.preventDefault();if(!getCart().length){alert("Your cart is empty.");return}let data=new FormData(f),c=getCart(),lines=c.map(x=>{let p=PRODUCTS.find(p=>p.id===x.id);return `${p.name} x${x.qty} - ${money(p.price*x.qty)}`}).join("\n");let sub=c.reduce((s,x)=>s+PRODUCTS.find(p=>p.id===x.id).price*x.qty,0),total=sub+10;let msg=`Hello UPTOWN FOOD, I want to place an order.\n\nCustomer: ${data.get("name")}\nPhone: ${data.get("phone")}\nOrder type: ${data.get("type")}\nAddress: ${data.get("address")||"Pickup"}\nNotes: ${data.get("notes")||"None"}\n\n${lines}\n\nDelivery: GH₵10\nTOTAL: ${money(total)}`;localStorage.setItem("lastOrder",msg);localStorage.removeItem("uptownCart");location.href="success.html"})}
function setupSuccess(){let a=document.getElementById("sendWhatsApp");if(a){let msg=localStorage.getItem("lastOrder")||"Hello UPTOWN FOOD, I would like to place an order.";a.href="https://wa.me/233599828219?text="+encodeURIComponent(msg)}}
document.addEventListener("DOMContentLoaded",()=>{updateCount();renderFeatured();renderMenu();renderCart();renderCheckout();setupCheckout();setupSuccess();document.querySelectorAll("#filters button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("#filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderMenu(b.dataset.cat)}));let params=new URLSearchParams(location.search);if(params.get("cat")){let cat=params.get("cat");renderMenu(cat);document.querySelectorAll("#filters button").forEach(b=>b.classList.toggle("active",b.dataset.cat===cat))}});
